#import "template.typ": *
#show: ams-article.with(
  title: [Implementing and Optimising the Shortest Vector Problem],
  authors: (
    (
      name: "Freddy Cunningham",
      department: [Department of Computer Science],
      organization: [Durham University],
      email: "freddy.t.cunningham@durham.ac.uk"
    ),
  ),
  bibliography-file: "refs.bib",
)

= Approach
I chose to use a brute-force approach to solve the shortest vector problem (SVP) as it provides an exact solution and is reasonably simple to implement. The algorithm I implemented was the Schnorr-Euchner Enumeration @Yasuda:2020, which uses polynomial-space which is less memory than the other main approach sieving which is an exponential-space algorithm. However, enumeration has a super-exponential run-time @Gama:2010 but is a natural choice as in practice it typically has good performance on low dimensions.

The run-time of enumeration algorithms is greatly affected by the quality of the input basis. A better basis is shorter and more orthogonal @Kumar:2019. I, therefore, chose to implement the LLL reduction algorithm @cryptoeprint:2023 to preprocess the lattice basis before running the enumeration algorithm.

I also make use of the Gaussian Heuristic @Yasuda:2020 to obtain an upper bound for the length of the shortest vector in the lattice. This is used to define the search space for the enumeration algorithm.

= Implementation
The primary issue I experienced whilst implementing my solution was working with floating-point values. I chose to implement the classical Gram-Schmidt orthogonalisation (GSO) with floating-point arithmetic (fpa). This is known to be numerically unstable and in the worst case when applied within the LLL algorithm the lattice basis will not necessarily be reduced at all because of inaccuracies in the GSO coefficients @Nguên_Stehlé_2005. I experienced these problems with my implementation on a number of different types of tests.

In practise a floating-point variant of the LLL algorithm, $L^2$ @Nguên_Stehlé_2005 is usually implemented which is proven to output a reduced basis in polynomial time. However, I was unable to successfully implement this algorithm.

= Run-time
To test the run-time of my implementation I generated uniform and knapsack like matrices of dimension $1 times 1$ to $30 times 30$ containing 32 bit numbers using the fplll library. To measure the run-time of my implementation I used hyperfine a command-line benchmarking tool. The tests were performed on a virtual machine with 4 cores and 8 GB RAM running an Ubuntu Linux image.

#figure(
  image("./images/mean_runtime_vs_dimensions_plot.png", width: 110%),
  caption: [Run-time in milliseconds plotted against the dimensionality of the basis for LLL delta parameter values of 0.75 and 0.99.],
) <run_time>

From @run_time we can see the program executes quicker using a delta value of 0.75 for low dimensional cases but slows down as the number of dimensions increase. This occurs because the quality of the basis reduction is lower for 0.75.

= Memory
To test the amount of memory my implementation used I measured the total bytes used throughout the entire execution of the program as well as the maximum number of bytes used at any point during the programs execution. This was done using the valgrind command line tool.

This test was repeated for lattices of dimensions 1, 2, 5, 10, 20 and 40. The results are shown in @memory_usage_table.

#figure(
  table(
    columns: 3,
    [*Dimensions*], [*Total bytes*], [*Max bytes*],
    [1], [$8,752$], [$8,712$],
    [2], [$8,880$], [$8,808$],
    [5], [$9,552$], [$9,384$],
    [10], [$11,632$], [$11,304$],
    [20], [$19,392$], [$18,744$],
    [40], [$49,312$], [$48,024$],
  ),
  caption: [Memory usage results for 32 bit knapsack test cases.],
) <memory_usage_table>

The results in @memory_usage_table follow the expected polynomial growth of the enumeration algorithm.

= Accuracy
To determine the accuracy of my implementation I compared my solution to the solution generated by the fplll library. Given the fplll module uses superior algorithms to deal with floating-point errors, for certain lattices my solution will be less accurate than that produced by fplll. This becomes more apparent the larger the dimension of the lattice basis. Therefore, I decided to allow a small tolerance level of $0.0001$ that my solution must be within in order to pass.

I ran my implementation on the same tests used to measure run-time and recorded the absolute difference between my solution and that generated by fplll and whether it passed given my specified tolerance. All tests passed for delta values of 0.75 and 0.99.

#figure(
  image("./images/accuracy_absolute_error_vs_dimensions_plot.png", width: 110%),
  caption: [Absolute error against dimensions for different values of delta.],
) <accuracy>

From @accuracy we can see that as the dimensionality of the lattice increases so does the absolute error of my solution. This is due to the floating-point errors introduced in my solution which are more apparent than those in the fplll library.
